#-------------------------------
# Site Settings

title: Fabian Gonzalez 
tab__title: Fabian Gonzalez ¡Todos podemos programar! Programación y tecnología
meta__title: Ingeniero de software en DEPT™. Artículos, vídeos, recursos y tutoriales sobre  programación, Frontend, JavaScript ☕️, React ⚛️, CSS y tecnología
logo: #'/images/logo.webp'
description: Ingeniero de software en DEPT™. Artículos, vídeos, recursos y tutoriales sobre  programación, Frontend, JavaScript ☕️, React ⚛️, CSS y tecnología

menu__settings:
  menu__items:
    - title: 'Principal'
      url: '/'
    - title: 'Proyectos'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Acerca de'
      url: '/acercade'
    - title: 'Links'
      url: '/links'
#    - title: 'Pages'
#      submenu:
#      - url: '/git'
#         title: 'Git & Github'


# Call to action button
cta__button__text: Cursos
cta__button_url: 'https://fabiangonzalez.dev/'

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/cover-image.webp'


#-------------------------------
# Author Settings

author:
  name: Fabian Gonzalez
  title: 👋Hola Fabian Gonzalez
  # bio: Art Director & Graphic Designer based in Australia, crafting beautiful and functional websites and mobile apps. When I’m not working, I’m probably listening to relaxing music or traveling somewhere.
  bio: "
   <b>Desarrollador Web Senior</b> en <b>Danone (Baufest)</b> con plataforma Adobe Experience Manager (AEM).<br/>
<b>Tecnologías</b>: HTML, CSS, Javascript, PHP, Mysql, Reactjs, NodeJS.<br/>
<b>Títulos</b>: de diseñador gráfico digital y Fullstack Developer + React (Universidad Tecnológica nacional). Además me encanta muchisimo el mundo Geek 🤓 "
  image: '/images/sato-avatar-full.webp'
  avatar: '/images/sato-avatar.webp'
  button__text: Ver mi trabajo


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Últimos <span class="text-span">Trabajos</span> # Add a 'text-span' class to highlight text.
  projects__description: "
    Todos mis últimos trabajos de desarrollo y diseño web.
    "


#-------------------------------
# Testimonials Section

testimonial__title: Mis  <span class="text-span">Clientes</span> # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: "Levi Robertson"
    image: "/images/testimonial-levi.jpeg"
    designation : "Host of JAMstack Phoenix"
    content : "The Angular Tutorial along with Fabian’s advice has completely changed my career..."

  - name: "Kaeside Iwuagwu"
    image: "/images/testimonial-kaeside.jpeg"
    designation : "Implementation Manager at WebMD"
    content : "Fabian has a knack for breaking down complex topics and keeps learning Angular fun."

  - name: "Matthew Knowles"
    image: "/images/testimonial-matthew.jpeg"
    designation : "Software Engineer"
    content : "If you are using Angular in a professional setting I can not recommend The Angular Tutorial highly enough."

  # - name: "Julie Arnold"
  #   image: "/images/client-4.webp"
  #   designation : "Full stack developer"
  #   content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


#-------------------------------
# Blog Section

blog__settings:
  blog__title: Posteos recientes del <span class="text-span">Blog</span> # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: fabiangonzalezdev@gmail.com # Add your email for contact form
  contact__title: Estate <span class="text-span">en contacto</span>  # Add a title to your form
  contact__description: ¿QUieres hablar de trabajo? ¿QUieres hablar de Webdev o diseño? ¡Acá estoy!. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Contáctate</span> Conmigo  # Add your title
  mailchimp__text: " 'Para hablar de trabajo', 'Para hablar de programación, Diseño y el mundo Geek ' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier:  http://eepurl.com/hIkfHr # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/Suscribite/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Mandame Whatsapp &nbsp; <i class="ion ion-logo-whatsapp"></i> # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: https-Fabian Gonzalez-github-io # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-EWFWEGYPFP # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/Fabian Gonzalezdev"}
- {icon: "ion-logo-github", link: "https://github.com/Fabian Gonzalez"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/Fabian Gonzalezdev/"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCXvmfLwOtwZS845_-WBFnnQ"}
# - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# - {icon: "ion-logo-codepen", link: "https://codepen.io"}
# - {icon: "ion-logo-vimeo", link: "https://vimeo.com"}
