#-------------------------------
# Site Settings

title: Fabian Gonzalez
tab__title: Fabian Gonzalez¡Todos podemos programar! Programación y tecnología
meta__title: Ingeniero de software en DEPT™. Artículos, vídeos, recursos y tutoriales sobre  programación, Frontend, JavaScript ☕️, React ⚛️, CSS y tecnología
logo: #'/assets/img/logo.webp'
description: Ingeniero de software en DEPT™. Artículos, vídeos, recursos y tutoriales sobre  programación, Frontend, JavaScript ☕️, React ⚛️, CSS y tecnología

menu__settings:
  menu__items:
    - title: 'Proyectos'
      url: '/projects/'
   #  - title: 'Blog'
    #   url: '/blog/'
   #  - title: 'Curriculum'
  #     url: '/curriculum'
    - title: 'Links'
      url: '/links'

   # - title: 'Servicios'
    #   url: '/servicios'
      
  #  - title: 'Cursos'
  #    submenu:
  #      - title: 'JavaScript'
  #       url: '/javascript'



# Call to action button
cta__button__text: Mi Curriculum
cta__button_url: '/servicesf'

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/assets/img/background.svg'


#-------------------------------
# Author Settings

author:
  name: Fabian Gonzalez
  title: Soluciones web que impulsan negocios y mejoran experiencias <i class="bi bi-rocket-takeoff"></i>
  # bio: Art Director & Graphic Designer based in Australia, crafting beautiful and functional websites and mobile apps. When I’m not working, I’m probably listening to relaxing music or traveling somewhere.
  bio: "
<b>Como desarrollador web senior, transformo ideas en plataformas digitales escalables, modernas y optimizadas para resultados.</b> "
  image: '/assets/img/600x600.webp'
  imageMobile: '/assets/img/avatar.png'
  avatar: '/assets/img/sato-avatar.webp'
  # button__text: Comienza tu proyecto hoy
  button__text2: Descubre cómo puedo ayudarte


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Últimos <span class="text-span">Trabajos</span> # Add a 'text-span' class to highlight text.
  projects__description: "Mis últimos trabajos de desarrollo web y diseño:"


#-------------------------------
# Testimonials Section

testimonial__title:  <span class="text-span">Testimonios</span> # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: "Jorge Rannin"
    image: "/assets/img/testimonials-georgie.jpg"
    designation : "Consultor Especialista Marketing"
    content : "Trabajar con Emanuel fue un gusto, gestionó y creo asesorías para AEM Cloud para el equipo de Colgate y Palmolive"

  - name: "Kaeside Iwuagwu"
    image: "/assets/img/testimonial2.png"
    designation : "Product Manager"
    content : "Trabajar con Emanuel fue una experiencia increíble para nuestra plataforma digital.  ¡Es un profesional excepcional"

  - name: "Matthew Knowles"
    image: "/assets/img/testimonial3.png"
    designation: "Director de Marketing en ORTHO CLINICAL"
    content: "Emanuel cumplió con todos los plazos y entregó un sitio web multilingüe impecable. Su atención al detalle y profesionalismo son insuperables."

#-------------------------------
# Blog Section

blog__settings:
  blog__title: ¿Quieres aprender más sobre <span class="text-span"> desarrollo web?</span> # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: fabiangonzalezdev@gmail.com # Add your email for contact form
  contact__title: Estate <span class="text-span">en contacto</span>  # Add a title to your form
  contact__description: ¿QUieres hablar de trabajo? ¿QUieres hablar de Webdev o diseño? ¡Acá estoy!. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Contáctate</span> Conmigo  # Add your title
  mailchimp__text: " 'Para hablar de trabajo', 'Para hablar de programación' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier:  http://eepurl.com/hIkfHr # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/Suscribite/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Envíame Whatsapp &nbsp; <i class="ion ion-logo-whatsapp"></i> # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: https-FabianGonzalez-github-io # add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google-analytics: G-0FJ2SRHHEC # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links

social:
- {icon: "ion-logo-twitter", link: "https://x.com/emasatodev"}
- {icon: "ion-logo-github", link: "https://github.com/fabiangonzalezdev"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/Fabian Gonzalez/"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/@emasatodev"}
- {icon: "ion-logo-tiktok", link: "https://www.tiktok.com/@emasatodev"}